AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CidrRange:
    Description: '1.1.1.0/16'
    Type: String
    Default: 73.73.0.0/24

Resources:
  # Create VPC 
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock : !Ref CidrRange
      EnableDnsHostnames : false
      EnableDnsSupport : false
      InstanceTenancy : 'default'
  Aurora:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DatabaseName: 'pantryDB'
      DBClusterIdentifier: 'pantryChef'
      MasterUsername: 'testusername'
      MasterUserPassword: 'testpassword'
      Engine: aurora
      EngineMode: serverless
      Port: 3306
      StorageEncrypted: True

  # This is where all the front-end VueJS content will go
  StaticContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: lepantrychef.com
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  # Allows all objects in the front-end bucket to have public read access (it is the WWW after all)
  StaticContentPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticContent
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - !Ref StaticContent
                  - "/*"
            Principal: "*"