name: Back-End Deployment
on:
  push:
    paths:
      - "back-end/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Upload artifact to s3 bucket to be referenced, this is only for the instantiation of the lambda for the CFT
      - name: Upload to s3 artifact bucket
        run: cd back-end/lambdas/profiles && zip -r profiles.zip * && aws s3 cp profiles.zip s3://lepantrychefartifacts

      # Deploy Lambda Profiles
      - name: Deploy Profile Lambda
        run: cd back-end/lambdas/profiles && zip -r profiles.zip * && aws lambda update-function-code --function-name pc-profile --zip-file fileb://profiles.zip

      # Recipe Lambda
      - name: Upload to s3 artifact bucket
        run: cd back-end/lambdas/recipes && zip -r recipes.zip * && aws s3 cp recipes.zip s3://lepantrychefartifacts

      - name: Deploy Recipe Lambda
        run: cd back-end/lambdas/recipes && zip -r recipes.zip * && aws lambda update-function-code --function-name pc-recipe --zip-file fileb://recipes.zip

      # Ingredient Lambda
      - name: Upload to s3 artifact bucket
        run: cd back-end/lambdas/ingredients && zip -r ingredients.zip * && aws s3 cp ingredients.zip s3://lepantrychefartifacts

      - name: Deploy Ingredient Lambda
        run: cd back-end/lambdas/ingredients && zip -r ingredients.zip * && aws lambda update-function-code --function-name pc-ingredient --zip-file fileb://ingredients.zip