name: Infrastructure
on:
  push:
    paths:
      - "infrastructure/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Upload template to s3 artifacts
      #- name: Upload Cloudformation Template
      #  run: cd infrastructure/cloudformation && zip -r profiles.zip * && aws lambda update-function-code --function-name NFAurora-DummyLambda-148PL7XXTJSZS --zip-file fileb://profiles.zip